### ISSUE TITLE
Cannot parse Firebase RSA key

### ISSUE THREAD

**Issue by alextekartik** [amaurel/rsa_pkcs#8]
Hi and thanks for the work. I'm using corsac_jwt which uses rsa_pkcs from parsing RSA public keys.

I cannot manage to parse keys (.RSAPKCSParser.parsePEM) got from <https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com> which are (I think) RSA keys but I could be wrong (doc https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library). It fails finding the correct header (and if i trick the headers, it fails with a `Failing Expected a value of type 'ASN1Integer', but got one of type 'ASN1Sequence` error).

Should this work somehow (i.e. it just a feature missing) or am I wrong in my usage?

Thanks

**Comment by amaurel** [comment]
Just publish a new version of the package ... please give it a try.

**Comment by alextekartik** [comment]
That was fast. Thanks it works perfectly. It is unfortunately incompatible with corsac_jwt so I had to use the following overridden dependencies:
```yaml
  rsa_pkcs: '>=1.1.2'
  asn1lib: '>=0.6.4'
```

I will warn corsac_jwt author. Thanks again
